development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: jasonkrezinski@gmail.com 
  :password: Nosaj!=9                 
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: jasonkrezinski@gmail.com 
  :password: Nosaj!=9 
  :enable_starttls_auto: true


  # I think something is wrong with the authentication