development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: h4aproject@gmail.com
  :password: health4all       
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: h4aproject@gmail.com
  :password: health4all 
  :enable_starttls_auto: true


  # I think something is wrong with the authentication